[project]
name = "multi"
version = "0.1.0"
description = "Custom multithreading and multiprocessing tool"
authors = [
  { name = "Hans" }
]

requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
